### ISSUE TITLE
401 Unauthorized returned on callback

### ISSUE THREAD

**Issue by trulysinclair** [TiotBenjy/ally-entra#1]
I've setup everything correctly as far as I know, I've double-checked the `clientId`, `clientSecret`, `callbackUrl`, and `tenantId`. Previously these values worked for the EntraProvider in Next Auth, but trying to use them for this package seems to just return a 401 Unauthorized. I've double-checked the route setup and callback handling as well but I can't figure out the issue.

I've gone into Entra and the sign-in logs show successful sign-ins with no blocks on the attempts. Is there anything I could be missing?

**Comment by trulysinclair** [comment]
This only happens when calling `await entra.user()`

**Comment by TiotBenjy** [comment]
Hello, 

Thanks for your issue i'll investigate

**Comment by TiotBenjy** [comment]
@trulysinclair 

I've just set up a test app on my machine and everything works.

To be able to help you better, please check the following items:
- Have you filled in the ENTRA_ID_CALLBACK_URL variable correctly?
- Does the ENTRA_ID_CALLBACK_URL variable correspond to the one defined in your application?

I need clarification on the following items:
- Which authorizationEndpoint do you use? ('common' or 'organizations' or 'consumers' or 'tenant')

If you'd like to make a reproduction repo so that I can guide you, but I think that for this error that the application is misconfigured.

**Comment by magnus-trent** [comment]
@TiotBenjy 

I'm attempting to set this up using the `tenant` endpoint, as `common` returns `invalid_request`. I'm still new to the Entra stuff I'm setting it up for my employer's organization, but I can confirm that the `clientId`, `clientSecret`, and `tenantId` are all accurate and up-to-date. In my case, the callback was also set to `http://localhost:3333/entra/callback` per your README. Which does successfully return the the `code` and other info. Adonis returns 500, yet also says 401 unauthorized.

It is my assumption that something must therefore be misconfigured but I cannot figure out what exactly may be the problem. Might I ask, what provider do you use? I think mine was setup with the session provider and I haven't touched it since then so if I need to change that please let me know. 

And of course, thank you for your help in this.

**Comment by magnus-trent** [comment]
Alright, this was my mistake. I had copied the secret ID, not the secret itself from Entra. Your library works perfectly as expected.

**Comment by TiotBenjy** [comment]
No problem, thanks for your issue !
