### ISSUE TITLE
[Bug]: CORS issues

### ISSUE THREAD

**Issue by magnus-trent** [TiotBenjy/ally-entra#3]
### Package version

1.0.1 (Default)

### authorizationEndpoint used in the configuration

tenant

### Describe the bug

Not sure if this is a bug or not, but I'm experiencing an issue I'm hoping you could help me with. I have a simple Adonis + Intertia/React + Ally + this package. My home page has `<Link href="/admin">Admin Panel</Link>`, and when I click on this link I encounter the following issue:

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://login.microsoftonline.com/***/oauth2/v2.0/authorize?redirect_uri=http%3A%2F%2Flocalhost%3A3333%2Fentra%2Fcallback&client_id=***&response_type=code&scope=openid+email&response_mode=query. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 200.
```

I've done a lot of investigating but I can't figure out why I'm encountering this. I'm running a dev localhost server, and maybe that's part of the problem but I don't encounter this issue in my Electron application. If you have any guidance, please help me.

**Note:** when I manually go to `http://localhost:3333/admin` I do not experience any issues. Only when clicking this link.

**Comment by TiotBenjy** [comment]
Hello,


Sorry for my late reply, I'll try to reproduce the problem.


If you can give me a deposit with the minimum code, that would be great 😀

**Comment by magnus-trent** [comment]
It's no problem, I'll fork what I have and strip out the private organization stuff and get back to you shortly

**Comment by magnus-trent** [comment]
Here is a gutted repo that's very close to what I've been trying to get working https://github.com/trulysinclair/demo-tower

**Comment by TiotBenjy** [comment]
thanks i'll check tomorrow

**Comment by TiotBenjy** [comment]
I've found your mistake 😅

In he home.tsx file at line 17 you use the inertia "`<Link />`" component instead of regular "`<a href>`" tag. In fact intertia can't fetch microsoft login page, the cross-origin error is normal :) 

(sorry for my bad english)

Information about inertia link component [docs](https://inertiajs.com/links) : "the Inertia <Link> component. This component is a light wrapper around a standard anchor <a> link that **intercepts click events and prevents full page reloads**"

You can now delete the reproduction repo if you want :)

**Comment by magnus-trent** [comment]
That's such a small oversight! Can't believe I missed that thank you so much
